-- Türkiye 81 il ve İstanbul 39 ilçe seed
INSERT INTO countries (code, name) VALUES ('TR', 'Türkiye') ON CONFLICT (code) DO NOTHING;

-- 81 il (cities) - country_code TR
INSERT INTO cities (country_code, name) VALUES
  ('TR', 'Adana'),
  ('TR', 'Adıyaman'),
  ('TR', 'Afyonkarahisar'),
  ('TR', 'Ağrı'),
  ('TR', 'Amasya'),
  ('TR', 'Ankara'),
  ('TR', 'Antalya'),
  ('TR', 'Artvin'),
  ('TR', 'Aydın'),
  ('TR', 'Balıkesir'),
  ('TR', 'Bilecik'),
  ('TR', 'Bingöl'),
  ('TR', 'Bitlis'),
  ('TR', 'Bolu'),
  ('TR', 'Burdur'),
  ('TR', 'Bursa'),
  ('TR', 'Çanakkale'),
  ('TR', 'Çankırı'),
  ('TR', 'Çorum'),
  ('TR', 'Denizli'),
  ('TR', 'Diyarbakır'),
  ('TR', 'Edirne'),
  ('TR', 'Elazığ'),
  ('TR', 'Erzincan'),
  ('TR', 'Erzurum'),
  ('TR', 'Eskişehir'),
  ('TR', 'Gaziantep'),
  ('TR', 'Giresun'),
  ('TR', 'Gümüşhane'),
  ('TR', 'Hakkari'),
  ('TR', 'Hatay'),
  ('TR', 'Isparta'),
  ('TR', 'Mersin'),
  ('TR', 'İstanbul'),
  ('TR', 'İzmir'),
  ('TR', 'Kars'),
  ('TR', 'Kastamonu'),
  ('TR', 'Kayseri'),
  ('TR', 'Kırklareli'),
  ('TR', 'Kırşehir'),
  ('TR', 'Kocaeli'),
  ('TR', 'Konya'),
  ('TR', 'Kütahya'),
  ('TR', 'Malatya'),
  ('TR', 'Manisa'),
  ('TR', 'Kahramanmaraş'),
  ('TR', 'Mardin'),
  ('TR', 'Muğla'),
  ('TR', 'Muş'),
  ('TR', 'Nevşehir'),
  ('TR', 'Niğde'),
  ('TR', 'Ordu'),
  ('TR', 'Rize'),
  ('TR', 'Sakarya'),
  ('TR', 'Samsun'),
  ('TR', 'Siirt'),
  ('TR', 'Sinop'),
  ('TR', 'Sivas'),
  ('TR', 'Tekirdağ'),
  ('TR', 'Tokat'),
  ('TR', 'Trabzon'),
  ('TR', 'Tunceli'),
  ('TR', 'Şanlıurfa'),
  ('TR', 'Uşak'),
  ('TR', 'Van'),
  ('TR', 'Yozgat'),
  ('TR', 'Zonguldak'),
  ('TR', 'Aksaray'),
  ('TR', 'Bayburt'),
  ('TR', 'Karaman'),
  ('TR', 'Kırıkkale'),
  ('TR', 'Batman'),
  ('TR', 'Şırnak'),
  ('TR', 'Bartın'),
  ('TR', 'Ardahan'),
  ('TR', 'Iğdır'),
  ('TR', 'Yalova'),
  ('TR', 'Karabük'),
  ('TR', 'Kilis'),
  ('TR', 'Osmaniye'),
  ('TR', 'Düzce')
ON CONFLICT (country_code, name) DO NOTHING;

-- İstanbul ilçeleri (39) - İstanbul city_id'ye bağlı
-- Önce İstanbul city_id'yi alıp areas ekleyeceğiz
DO $$
DECLARE
  istanbul_id uuid;
BEGIN
  SELECT id INTO istanbul_id FROM cities WHERE country_code = 'TR' AND name = 'İstanbul' LIMIT 1;
  IF istanbul_id IS NOT NULL THEN
    INSERT INTO areas (id, city_id, name) VALUES
      (gen_random_uuid(), istanbul_id, 'Adalar'),
      (gen_random_uuid(), istanbul_id, 'Arnavutköy'),
      (gen_random_uuid(), istanbul_id, 'Ataşehir'),
      (gen_random_uuid(), istanbul_id, 'Avcılar'),
      (gen_random_uuid(), istanbul_id, 'Bağcılar'),
      (gen_random_uuid(), istanbul_id, 'Bahçelievler'),
      (gen_random_uuid(), istanbul_id, 'Bakırköy'),
      (gen_random_uuid(), istanbul_id, 'Başakşehir'),
      (gen_random_uuid(), istanbul_id, 'Bayrampaşa'),
      (gen_random_uuid(), istanbul_id, 'Beşiktaş'),
      (gen_random_uuid(), istanbul_id, 'Beykoz'),
      (gen_random_uuid(), istanbul_id, 'Beylikdüzü'),
      (gen_random_uuid(), istanbul_id, 'Beyoğlu'),
      (gen_random_uuid(), istanbul_id, 'Büyükçekmece'),
      (gen_random_uuid(), istanbul_id, 'Çatalca'),
      (gen_random_uuid(), istanbul_id, 'Çekmeköy'),
      (gen_random_uuid(), istanbul_id, 'Esenler'),
      (gen_random_uuid(), istanbul_id, 'Esenyurt'),
      (gen_random_uuid(), istanbul_id, 'Eyüpsultan'),
      (gen_random_uuid(), istanbul_id, 'Fatih'),
      (gen_random_uuid(), istanbul_id, 'Gaziosmanpaşa'),
      (gen_random_uuid(), istanbul_id, 'Güngören'),
      (gen_random_uuid(), istanbul_id, 'Kadıköy'),
      (gen_random_uuid(), istanbul_id, 'Kağıthane'),
      (gen_random_uuid(), istanbul_id, 'Kartal'),
      (gen_random_uuid(), istanbul_id, 'Küçükçekmece'),
      (gen_random_uuid(), istanbul_id, 'Maltepe'),
      (gen_random_uuid(), istanbul_id, 'Pendik'),
      (gen_random_uuid(), istanbul_id, 'Sancaktepe'),
      (gen_random_uuid(), istanbul_id, 'Sarıyer'),
      (gen_random_uuid(), istanbul_id, 'Silivri'),
      (gen_random_uuid(), istanbul_id, 'Sultanbeyli'),
      (gen_random_uuid(), istanbul_id, 'Sultangazi'),
      (gen_random_uuid(), istanbul_id, 'Şile'),
      (gen_random_uuid(), istanbul_id, 'Şişli'),
      (gen_random_uuid(), istanbul_id, 'Tuzla'),
      (gen_random_uuid(), istanbul_id, 'Ümraniye'),
      (gen_random_uuid(), istanbul_id, 'Üsküdar'),
      (gen_random_uuid(), istanbul_id, 'Zeytinburnu')
    ON CONFLICT (city_id, name) DO NOTHING;
  END IF;
END $$;
